# Generated by Django 3.1 on 2023-11-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
