# Generated by Django 4.2.3 on 2023-09-26 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='brand.brand'),
            preserve_default=False,
        ),
    ]
