# Generated by Django 3.1 on 2023-11-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_proddeal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='marked_price',
        ),
    ]
