# Generated by Django 3.1 on 2023-11-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20231109_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Discount_price',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
