# Generated by Django 5.0.1 on 2024-05-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_proddeal_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producttimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_end_date', models.DateTimeField()),
            ],
        ),
    ]
