# Generated by Django 5.0.1 on 2024-05-13 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_producttimer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producttimer',
        ),
    ]
