# Generated by Django 3.1 on 2023-11-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20231106_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount', models.PositiveIntegerField(help_text='discount in percentage')),
                ('active', models.BooleanField(default=True)),
                ('active_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
