# Generated by Django 3.1 on 2023-11-06 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20231106_1109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
