# Generated by Django 3.1 on 2023-11-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_delete_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
            ],
        ),
    ]
