# Generated by Django 3.1 on 2023-11-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_auto_20231106_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='product',
            new_name='products',
        ),
    ]
