# Generated by Django 3.1 on 2023-11-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20231106_1035'),
        ('carts', '0011_auto_20231107_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='products',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='products',
            field=models.ManyToManyField(to='store.Product'),
        ),
    ]
