# Generated by Django 3.1 on 2023-11-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_wishlistitem_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
