# Generated by Django 3.1 on 2023-11-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0014_wishlistitem_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='images',
        ),
    ]
