# Generated by Django 5.0.1 on 2024-08-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0023_alter_cart_id_alter_cartitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
            preserve_default=False,
        ),
    ]
