# Generated by Django 3.1 on 2023-11-18 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_sub_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub_category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
