# Generated by Django 3.1 on 2023-11-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20231118_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub_category',
            options={'verbose_name': 'sub_category', 'verbose_name_plural': 'sub_categories'},
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
