# Generated by Django 3.1 on 2023-11-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20231118_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='slug',
            new_name='subslug',
        ),
    ]
