# Generated by Django 3.1 on 2023-11-06 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
    ]
